name: rinha

services:
  api:
    build: .
    image: rinha:1.0.0
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`api.rinha.localhost`)"
        - "traefik.http.routers.api.entrypoints=web"
        - "traefik.http.services.api.loadbalancer.server.port=8000"
        - "traefik.http.middlewares.api-ratelimit.ratelimit.average=3"
        - "traefik.http.middlewares.api-ratelimit.ratelimit.burst=10"
        - "traefik.http.routers.api.middlewares=api-ratelimit"
    depends_on:
      - db

  db:
    image: postgres:17.6
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  traefik:
    image: "traefik:v3.5"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.rinha.localhost`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.service=api@internal"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  postgres_data: