# Generated by Django 5.2.5 on 2025-08-29 19:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fighters", "0005_alter_occupation_name_alter_trait_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Arena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="The location of the arena",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the arena",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arena",
                "verbose_name_plural": "Arenas",
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="What happened in this match",
                        verbose_name="description",
                    ),
                ),
                (
                    "max_number_of_rounds",
                    models.PositiveIntegerField(
                        default=3, help_text="Max number of rounds in the match"
                    ),
                ),
                (
                    "finished",
                    models.BooleanField(
                        default=False, help_text="Indicates if the match is over"
                    ),
                ),
                (
                    "arena",
                    models.ForeignKey(
                        help_text="Arena where this match takes place",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="arenas.arena",
                    ),
                ),
                (
                    "fighters",
                    models.ManyToManyField(
                        help_text="Fighters in this match",
                        related_name="matches",
                        to="fighters.fighter",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        help_text="The fighter who won the match",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="won_matches",
                        to="fighters.fighter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matches",
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "round_number",
                    models.PositiveIntegerField(
                        help_text="The number of this round in the match",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="What happened in this round.",
                        verbose_name="description",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        help_text="The match this round belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="arenas.match",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        help_text="The fighter who won this round",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="won_rounds",
                        to="fighters.fighter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Round",
                "verbose_name_plural": "Rounds",
            },
        ),
    ]
