# Generated by Django 5.2.5 on 2025-08-30 00:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arenas", "0001_initial"),
        ("fighters", "0005_alter_occupation_name_alter_trait_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="description",
        ),
        migrations.RemoveField(
            model_name="match",
            name="finished",
        ),
        migrations.RemoveField(
            model_name="match",
            name="winner",
        ),
        migrations.AddField(
            model_name="match",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="When the match was created",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="round",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                help_text="The fighter who won this round (null for draw rounds)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="won_rounds",
                to="fighters.fighter",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="round",
            unique_together={("match", "round_number")},
        ),
        migrations.CreateModel(
            name="MatchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result_type",
                    models.CharField(
                        choices=[("win", "Victory"), ("draw", "Draw")],
                        help_text="The result type of the match",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the match result"),
                ),
                (
                    "match",
                    models.OneToOneField(
                        help_text="The match this result belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="arenas.match",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        help_text="The fighter who won the match",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="won_matches",
                        to="fighters.fighter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match Result",
                "verbose_name_plural": "Match Results",
            },
        ),
    ]
