# Generated by Django 5.2.5 on 2025-08-30 02:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arenas", "0003_alter_matchresult_result_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="title",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="The title of the match",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
