# Generated by Django 5.2.5 on 2025-08-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Trait",
                "verbose_name_plural": "Traits",
            },
        ),
        migrations.AddField(
            model_name="fighter",
            name="traits",
            field=models.ManyToManyField(
                blank=True, related_name="fighters", to="fighters.trait"
            ),
        ),
    ]
