# Generated by Django 5.2.5 on 2025-08-25 18:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighters", "0003_occupation_fighter_occupation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fighter",
            name="description",
        ),
        migrations.AddField(
            model_name="fighter",
            name="biography",
            field=models.TextField(
                default=django.utils.timezone.now, verbose_name="Biography"
            ),
            preserve_default=False,
        ),
    ]
