# Generated by Django 5.2.5 on 2025-08-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighters", "0004_remove_fighter_description_fighter_biography"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occupation",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="trait",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
